language: r
sudo: false
cache: packages
dist: trusty

addons:
  apt:
    packages:
      - libv8-dev

r_check_args: "--as-cran --run-dontrun"

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: Y7ly6rxiG4EBAKKREFovZ1LPQp2ghrN7ThIfkMaQ1XCQLRV0D39a3Uuf1UigS6gpqrtaedXakbtZwG3CIhICILRRiQSZch3gGZUNMRkVrG/0wZDn7HwWOquTxPJEeH1AUlKYToxiI6rRqd/c3U4FwisKuIUHmvqDRA1NEtdiqJY=
